framework: golang
version: "1.2.0"
# blocklist:
#   - "/home/nucleus/repo/context_test.go##TestContextRenderFile"
#   - "/home/nucleus/repo/routes_test.go##TestRouterMiddlewareAndStatic"
#   - "/home/nucleus/repo/routes_test.go##TestRouterNotFound"
preRun:
  command:
    - "go mod init"
    - "go get -d ./..." 
    - "go get -u github.com/golang/protobuf/protoc-gen-go"
    - "go mod why github.com/golang/protobuf"
    - "go get -t github.com/gin-gonic/gin"
    - "go mod vendor" 

postMerge:
 pattern:
    - ""
